### ISSUE TITLE
Update ReadTheDocs build configuration

### ISSUE THREAD

**Issue by cthoyt** [scolby33/easy_config#25]
Click isn't getting built properly. See: https://easy-config.readthedocs.io/en/latest/contrib/click.html

Solution: use a .readthedocs.yml file that looks like this:
```yaml
# See: https://docs.readthedocs.io/en/latest/yaml-config.html
python:
  version: 3
  pip_install: true
  extra_requirements:
    - docs
    - contrib_click
```

Also, add an extras in `setup.cfg` for docs that includes this:
```ini
[options.extras_require]
docs =
    sphinx
    sphinx-rtd-theme
    sphinx-click
    sphinx-autodoc-typehints
```
